<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Georgi Orozov">

    <!-- Bootstrap CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
</head>

<body>
    <div class="container">
        <h1>Calculator</h1>

        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="get">
            <div class="form-row">
                <div class="col">
                    <input type="text" class="form-control" name="expression" placeholder="Write your expression here">
                </div>
            </div>
            <button type="submit" name="submit" value="submit" class="btn btn-primary">Calculate</button>
        </form>
        <p>The answer is: <?php echo $view->result; ?></p>
    </div>





    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
</body>

</html>
